version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release
environment:
 COVERALLS_REPO_TOKEN:
   secure: EUMspW33GYW5M5sNskOBWO4ElP1tKWOUI
build_script:
 - dotnet restore
 - dotnet build
 - cd ./TeleBillingAPIXUnit.Tests && dotnet test
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\bin\Debug\TeleBillingAPIXUnit.Tests.dll -noshadow" -output:"coverage.xml"
