version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release
environment:
 COVERALLS_REPO_TOKEN:
   secure: EUMspW33GYW5M5sNskOBWO4ElP1tKWOUI
build_script:
 - dotnet restore
 - dotnet build
 - cd ./TeleBillingAPIXUnit.Tests && dotnet test && cd.. && cd User
 - tree /F
test_script:

