version: 1.0.{build}
os: Visual Studio 2015
skip_tags: true
configuration: Release
cache:
- "%LOCALAPPDATA%\\Yarn"
build_script:
- ps: dotnet restore
build:
  project: .\TeleBillingAPI.sln
  verbosity: minimal